services:
  sol_agent:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD","python","-c","import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/health').status==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 5

  tunnel:
    image: cloudflare/cloudflared:2025.8.1
    command: ["tunnel","--no-autoupdate","run"]
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      sol_agent:
        condition: service_healthy
    restart: unless-stopped
